//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonCode
    {
        public string CommonTypeID { get; set; }
        public string CommonID { get; set; }
        public string StrValue1 { get; set; }
        public string StrValue2 { get; set; }
        public Nullable<decimal> NumValue1 { get; set; }
        public Nullable<decimal> NumValue2 { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string NoteOfUsage { get; set; }
    }
}
