//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReport
    {
        public long id { get; set; }
        public string ObjectID { get; set; }
        public string DRType { get; set; }
        public string Content { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public string Approval { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> AppPer { get; set; }
        public string HRComment { get; set; }
        public string HRCommentBy { get; set; }
        public Nullable<int> HRPer { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DateOfReport { get; set; }
        public Nullable<bool> ApproveComplete { get; set; }
        public Nullable<bool> HRCommentComplete { get; set; }
    }
}
