//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSample
    {
        public string DocumentCode { get; set; }
        public string DocumentName { get; set; }
        public string Description { get; set; }
        public string DocumentType { get; set; }
        public Nullable<int> Priority { get; set; }
        public string PreparedBy { get; set; }
        public string SubmitedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IssueDepartment { get; set; }
        public string Language { get; set; }
    }
}
