//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string ObjectID { get; set; }
        public string PositionID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RefNo { get; set; }
        public string Note { get; set; }
        public string EmployeeType { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string DRFeedbackers { get; set; }
        public string ReportTo { get; set; }
        public string HRTo { get; set; }
        public string WorkingType { get; set; }
        public string ContractLink { get; set; }
    }
}
