//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamLib
    {
        public long id { get; set; }
        public Nullable<long> ExamID { get; set; }
        public string Question { get; set; }
        public string QuestionURL { get; set; }
        public string Answer { get; set; }
        public string AnswerURL { get; set; }
    }
}
