//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public string ObjectID { get; set; }
        public string ObjectGroup { get; set; }
        public string ObjectType { get; set; }
        public string FullName { get; set; }
        public string PID { get; set; }
        public Nullable<System.DateTime> PIDDate { get; set; }
        public string PIDIssue { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string PoB { get; set; }
        public string PerAdd { get; set; }
        public string TemAdd { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string LocationID { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string TaxCode { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> TKMID { get; set; }
        public string WAID { get; set; }
    }
}
