//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollEmployeeDetail
    {
        public string PayrollID { get; set; }
        public string ObjectID { get; set; }
        public string PayType { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Qty { get; set; }
        public string Price { get; set; }
        public string PayAmt { get; set; }
        public string Note { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> Negative { get; set; }
        public string Status { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RefID { get; set; }
    }
}
