//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleSkill
    {
        public long id { get; set; }
        public Nullable<long> SkillSetID { get; set; }
        public string ObjectID { get; set; }
        public Nullable<int> SeftEvaluate { get; set; }
        public Nullable<int> YearOfExperience { get; set; }
        public string ProjectName { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
