//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public string PositionID { get; set; }
        public string PositionName { get; set; }
        public string JobDescription { get; set; }
        public string JobLevel { get; set; }
        public string JobRequirement { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string DepartmentID { get; set; }
        public string JobCategory { get; set; }
        public string WorkLocation { get; set; }
        public string SalaryType { get; set; }
        public string PreferLang { get; set; }
        public string PositionType { get; set; }
        public string ManageGroup { get; set; }
    }
}
