//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Menu_Module
    {
        public string RoleID { get; set; }
        public string ObjectUDAffect { get; set; }
        public string ObjectType { get; set; }
        public string ModuleID { get; set; }
        public Nullable<bool> AllowNew { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
        public Nullable<bool> AllowDelete { get; set; }
        public Nullable<bool> AllowView { get; set; }
        public Nullable<bool> AllowPrint { get; set; }
        public Nullable<bool> AllowDownload { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
