//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKDetail
    {
        public long id { get; set; }
        public string TimeKeepID { get; set; }
        public string ObjectID { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
        public string TotalHour { get; set; }
        public string TypeOfDay { get; set; }
        public string Note { get; set; }
        public string RefID { get; set; }
    }
}
