//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingTaskHistory
    {
        public long id { get; set; }
        public string TaskID { get; set; }
        public string ActionBy { get; set; }
        public string Action { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
    }
}
